# tasks file for dump-init
---
- name: create (download) directory
  file:
    path: "{{ dump_init_downloads_path }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  tags:
    - dump-init-install-binary-download
    - dump-init-install-binary-download-directory

- name: download
  get_url:
    url: "https://github.com/Yelp/dumb-init/releases/download/v{{ dump_init_version }}/dumb-init_{{ dump_init_version }}_{{ dump_init_machine_map[ansible_machine] }}"
    dest: "{{ dump_init_downloads_path }}/dump-init-{{ dump_init_machine_map[ansible_machine] }}-{{ dump_init_version }}"
    owner: root
    group: root
    mode: 0755
  tags:
    - dump-init-install-binary-download
    - dump-init-install-binary-download-get

- name: install
  file:
    src: "{{ dump_init_downloads_path }}/dump-init-{{ dump_init_machine_map[ansible_machine] }}-{{ dump_init_version }}"
    dest: "{{ dump_init_install_prefix }}/dump-init"
    state: link
    force: true
  tags:
    - dump-init-install-binary-install
    - dump-init-install-binary-install-symlink
