# tasks file
---
- name: create (download) directory
  ansible.builtin.file:
    path: "{{ dumb_init_downloads_path }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  tags:
    - dumb-init-install-binary-download
    - dumb-init-install-binary-download-directory

- name: download
  ansible.builtin.get_url:
    url: "https://github.com/Yelp/dumb-init/releases/download/v{{ dumb_init_version }}/dumb-init_{{ dumb_init_version }}_{{ dumb_init_machine_map[ansible_machine] }}"
    dest: "{{ dumb_init_downloads_path }}/dumb-init-{{ dumb_init_machine_map[ansible_machine] }}-{{ dumb_init_version }}"
    owner: root
    group: root
    mode: 0755
  tags:
    - dumb-init-install-binary-download
    - dumb-init-install-binary-download-get

- name: install
  ansible.builtin.file:
    src: "{{ dumb_init_downloads_path }}/dumb-init-{{ dumb_init_machine_map[ansible_machine] }}-{{ dumb_init_version }}"
    dest: "{{ dumb_init_install_prefix }}/dumb-init"
    state: link
    force: true
  tags:
    - dumb-init-install-binary-install
    - dumb-init-install-binary-install-symlink
